### ISSUE TITLE
Add Jasmine Unit Tests To Build

### ISSUE THREAD

**Issue by VoltiSubito** [jeffbrown/five15#5]

**Comment by craigburke** [comment]
I have a Gradle task to do this on another project, it might be helpful for this;
https://github.com/craigburke/angular-grails3/blob/master/build.gradle#L86

**Comment by craigburke** [comment]
I can grab this one unless you wanted to do it, @VoltiSubito.

**Comment by VoltiSubito** [comment]
Go for it.

**Comment by VoltiSubito** [comment]
As a side note, as far as I'm concerned anyone can work on any item they wish in the project.  @jeffbrown may feel differently.

**Comment by craigburke** [comment]
@VoltiSubito I definitely don't want to step on anyone's toes here, so I appreciate that.

I'm not afraid of @jeffbrown. Just kidding, I'm actually completely terrified of him. I heard he once killed a :bear: by punching it in the face.

**Comment by craigburke** [comment]
I'm looking at how to best organize the jasmine tests and I'm a bit torn. I find the rationale for including the tests in the same place as the JS source pretty compelling:
https://github.com/johnpapa/angular-styleguide#style-y197

On the other hand placing them somewhere like src/test/js is nice too because it groups them with the Groovy tests. What's your take on that @VoltiSubito?

**Comment by VoltiSubito** [comment]
@craigburke my preference is to have the tests side by side with the implementation with a *.spec.js filename.  Since part of this project is how to best marry the Grails and Angular universes I think we should consider breaking from the style guides where it makes sense.

How's that for not-an-answer. :smile: 

My thought is to follow the style guide unless we can name one or more concrete benefits of doing otherwise because of something in the Grails ecosystem.

**Comment by craigburke** [comment]
@VoltiSubito that's the same non-conclusion I've come to :smile: 

The benefit I see of breaking from the style guide is consistency (since we don't have tests interspersed with source in the Groovy part of the app). I think people would expect in a groovy/java project that tests are in src/test. Here's an example of what that might look like:
https://github.com/craigburke/angular-grails3/tree/master/src/test

We can also go the side by side route although it will require adding some exclusions to the asset pipeline so that .spec.js files aren't processed or packaged. I don't think that's a huge deal but a minor con for that particular approach. We could definitely make the case for either.

I don't know if the consistency and lack of AP configuration is a compelling enough argument. What are your thoughts?

**Comment by craigburke** [comment]
Need to resolve #15 in order to run the tests without a ton of exclusions in the karma config.

**Comment by VoltiSubito** [comment]
@craigburke the way I'm reasoning about it currently is: If we see our primary audience as Grails people adopting Angular, we should do things that wouldn't surprise a Grails person.  I can see that as reason enough for putting the specs in a different folder.  I don't personally love it but I understand the reasoning.

We can always move stuff later if we change our minds as well.

**Comment by craigburke** [comment]
@VoltiSubito I set things up so that the tests are in place with the code and it looks pretty good actually. Thanks for hashing it out with me.

**Comment by VoltiSubito** [comment]
:+1:
